version: 2
jobs:
  build:
    docker:
      # - image: circleci/python:3.6
      - image: circleci/python:3.6.2-stretch-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run: mkdir reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.0.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.0.jar -log reports/selenium.log
          background: true
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running unit tests
          command: |
            . venv/bin/activate
            python3 manage.py test
          background: true
      - run:
          name: Migrate DB changes
          command: |
            . venv/bin/activate
            python manage.py migrate
      - run:
          name: Start server
          command: |
            python manage.py runserver 8000 &
            sleep 10
          background: true
      - run:
          name: Run behave tests
          command: |
            . venv/bin/activate
            behave --junit
      - store_artifacts:
          path: reports/
          destination: python_app
      - store_test_results:
          path: reports/